---
slug: :mikutter-datasource-weather
depends:
  mikutter: 3.2.0
  plugin:
  - settings
version: '0.0.2'
author: moguno
name: mikutter-datasource-weather
description: livedoorのWeather Hacksを使ってお天気情報を表示するデータソースです。
